### ISSUE TITLE
When stylefile is unchecked it still adds it in the ts file

### ISSUE THREAD

**Issue by unnarb** [pavel-agarkov/vs-ngx-item-templates#5]
styleUrls: ['./x.scss']

Should not be any styleurl defined

**Comment by pavel-agarkov** [comment]
Yes, unfortunatelly there is no way to include any conditions into the template.
Right now template looks like a proper ts https://github.com/pavel-agarkov/vs-ngx-item-templates/blob/182e5889e25b643914f1a178355ea951b9f62f76/AngularTemplates/component.component.ts#L3-L7
In order to implement it the way you've described there should be a more complex variable that will include entire line https://github.com/pavel-agarkov/vs-ngx-item-templates/blob/182e5889e25b643914f1a178355ea951b9f62f76/AngularTemplates/component.component.ts#L6
I didn't want to do it this way and I like to always have styles even if they are empty (for the future)
You can fork and implement it differently.
